theme: jekyll-theme-minimal
title: Uroš Herman
description: Contact
GSEFM, Goethe University Frankfurt
Campus Westend
Theodor-W.-Adorno-Platz 3
60629, Frankfurt am Main
uros.herman@hof.uni-frankfurt.de
herman.uros@gmail.com
logo: UHTwitter.jpg
github:
 is_user_page: false
 is_project_page: false
